const secPrograms = [
  {
    university: 'University of Alabama',
    nickname: 'Crimson Tide',
    mascot: 'Big Al',
    yearFounded: 1892,
    lifetimeRecord: { wins: 995, losses: 316, ties: 42 },
  },
  {
    university: 'Auburn University',
    nickname: 'Tigers',
    mascot: 'Aubie',
    yearFounded: 1892,
    lifetimeRecord: { wins: 782, losses: 473, ties: 42 },
  },
  {
    university: 'University of Arkansas',
    nickname: 'Razorbacks',
    mascot: 'Tusk / Big Red (Razorback)',
    yearFounded: 1894,
    lifetimeRecord: { wins: 740, losses: 539, ties: 40 },
  },
  {
    university: 'University of Florida',
    nickname: 'Gators',
    mascot: 'Albert & Alberta Gator',
    yearFounded: 1906,
    lifetimeRecord: { wins: 744, losses: 446, ties: 37 },
  },
  {
    university: 'University of Georgia',
    nickname: 'Bulldogs',
    mascot: 'Uga (live bulldog)',
    yearFounded: 1892,
    lifetimeRecord: { wins: 890, losses: 431, ties: 54 },
  },
  {
    university: 'University of Kentucky',
    nickname: 'Wildcats',
    mascot: 'Wildcat (Scratch / Blue)',
    yearFounded: 1881,
    lifetimeRecord: { wins: 657, losses: 655, ties: 44 },
  },
  {
    university: 'Louisiana State University (LSU)',
    nickname: 'Tigers',
    mascot: 'Mike the Tiger',
    yearFounded: 1893,
    lifetimeRecord: { wins: 827, losses: 428, ties: 47 },
  },
  {
    university: 'Mississippi State University',
    nickname: 'Bulldogs',
    mascot: 'Bully',
    yearFounded: 1895,
    lifetimeRecord: { wins: 610, losses: 593, ties: 37 },
  },
  {
    university: 'University of Missouri',
    nickname: 'Tigers',
    mascot: 'Truman the Tiger',
    yearFounded: 1890,
    lifetimeRecord: { wins: 721, losses: 593, ties: 52 },
  },
  {
    university: 'University of Mississippi (Ole Miss)',
    nickname: 'Rebels',
    mascot: 'Tony the Landshark / Colonel Reb (historical)',
    yearFounded: 1893,
    lifetimeRecord: { wins: 713, losses: 549, ties: 35 },
  },
  {
    university: 'University of South Carolina',
    nickname: 'Gamecocks',
    mascot: 'Cocky',
    yearFounded: 1892,
    lifetimeRecord: { wins: 653, losses: 621, ties: 44 },
  },
  {
    university: 'University of Tennessee',
    nickname: 'Volunteers',
    mascot: 'Smokey',
    yearFounded: 1891,
    lifetimeRecord: { wins: 870, losses: 415, ties: 53 },
  },
  {
    university: 'Texas A&M University',
    nickname: 'Aggies',
    mascot: 'Reveille',
    yearFounded: 1894,
    lifetimeRecord: { wins: 772, losses: 496, ties: 44 },
  },
  {
    university: 'Vanderbilt University',
    nickname: 'Commodores',
    mascot: 'Mr. Commodore',
    yearFounded: 1890,
    lifetimeRecord: { wins: 625, losses: 671, ties: 50 },
  },
  {
    university: 'University of Texas',
    nickname: 'Longhorns',
    mascot: 'Bevo',
    yearFounded: 1893,
    lifetimeRecord: { wins: 916, losses: 387, ties: 32 },
  },
  {
    university: 'University of Oklahoma',
    nickname: 'Sooners',
    mascot: 'Boomer & Sooner',
    yearFounded: 1895,
    lifetimeRecord: { wins: 950, losses: 348, ties: 53 },
  },
];

export default secPrograms;
